### ISSUE TITLE
GOXLR-Mini does not work

### ISSUE THREAD

**Issue by GabrielZacarias** [Adelenade/GoXlr-Macos#17]
The goxlr-mini isn't working at all, the app won't pick it up and / or the daemon can't initialise it.

This issue is due to the system agent that initialises as root the goxlr when plugged in. As the agent looks for a device with the device ID of a full GoXlr, it doesn't pick up the mini.

・Fix :
You can edit the file:

`/Library/LaunchAgents/com.adesky.goxlr.plist`

and change the id as below:

```
<key>idProduct</key>
<integer>36836</integer>
```

then do in Terminal:

```
launchctl unload /Library/LaunchAgents/com.adesky.goxlr.plist
launchctl load /Library/LaunchAgents/com.adesky.goxlr.plist
```

**Comment by Adelenade** [comment]
Closed as already fixed ! (i'm in vacation right now so the commit may take some days but it's fixed in my local work, just needed to delete some lines of code)

Oh and for future issues that I post on discord : "Known issues" means that I already know the issue and I'm working on ! So no need to open a github issue !
