### ISSUE TITLE
GoXlr-Mini compatibility - Does not recognize GoXLR

### ISSUE THREAD

**Issue by Joinatic** [Adelenade/GoXlr-Macos#6]
Hi,
I followed the steps in your readme and it seems, that it wont recognize my GoXLR Mini. Is it possible, that the driver is not supported by M1?

Im on a Mac Studio M1 Max with Monterey.

Tell me if you need more information

**Comment by Adelenade** [comment]
Hi ! First of all, thanks for telling me about this (huge) problem !

Don't worry, the driver is fully compatible with M1, the problem is more - i think - about the Mini. 
The problem is that I can't really fix it ! I don't know exactly why it isn't working but I'm actually working on a brand new version of the app that requires a full re-write, and even if i still have the old code I prefer fix this bug for the next version.

BUT ! Even if this app itself will not really work for some time, you can use the "goxlr-utility" mentionned in the readme. It's a CLI tool but that actually FULLY support the mini. Infact all the functionalities of the utility are going to be in the new version but i don't have any goxlr-mini to test it !

So I wanted to know if you have any discord account to help me testing the new app with a goxlr mini (and with a M1 mac, bcause i have a Intel 😢) !

And sorry for the problems you get by using the app !

**Comment by AndreaSekai** [comment]
Hi !
I have quite the same problem as indicated by @Joinatic with the same Mac System. I will be glad to test the app for M1 (I was already thinking of sending the GoXRL back and will do so if I don't find a solution by the end of the week) and share my Discord account if that helps. 

Thank you for your help !

**Comment by Adelenade** [comment]
Okay ! If you have the latest version of the app you don't need to bother you about installing the daemon ! All you need is libusb (`brew install libusb`) !

BUT ! For now like I said earlier the app may not work with the mini, but it's still completely possible to use the mini on a m1 mac. You just need to build and use the [GoXlr-Utility](https://github.com/GoXLR-on-Linux/goxlr-utility) ! If you have any trouble installing or using it, I can help you ! (If the problem is directly linked to the daemon/client itself i will ask the devs if needed)

To summarise:

- The daemon isn't needed for the app itself but if the app isn't working you'll need to install it.
- The utility, packaging the daemon and a cli can be found and installed from [here](https://github.com/GoXLR-on-Linux/goxlr-utility).
- The input/output creation creates some aggregate devices that redirects the sound to the right channels of the GoXlr, and it's not linked with the daemon/utility. You have a AUDIO part of the goxlr / app with theses audio devices and an USB part, that manages all the settings, the channel volumes and everything else. If the audio part work it doesn't mean that the device is fully working !

Feel free to tell me if theses answers helped you understanding more about what you asked !

**Comment by MiraiSubject** [comment]
When running the goxlr-daemon that's packaged in https://github.com/Adelenade/GoXlr-Macos/releases/tag/1.1.2 separately. I get the following logs: 

```
22:59:38 [WARN] Removing unused socket file /tmp/goxlr.socket
22:59:38 [INFO] Connected to possible GoXLR device at Bus 001 Device 004: ID 1220:8fe4
[usb/src/goxlr.rs:77] handle.set_active_configuration(1) = Ok(
    (),
)
22:59:38 [INFO] Attempting to initialise device..
22:59:38 [ERROR] Couldn't load potential GoXLR on bus 1 address 4: USB error: Operation not supported or unimplemented on this platform
22:59:48 [INFO] Connected to possible GoXLR device at Bus 001 Device 004: ID 1220:8fe4
[usb/src/goxlr.rs:77] handle.set_active_configuration(1) = Ok(
    (),
)
```

This is also a GoXLR Mini on an M1 Pro Macbook. Trying to invoke the goxlr-client gives the error that multiple devices are connected. 

This is the libusb version that I have installed: 

```
❯ brew install libusb
Warning: libusb 1.0.26 is already installed and up-to-date.
To reinstall 1.0.26, run:
  brew reinstall libusb
```

**Comment by Adelenade** [comment]
Hmmm, this error can be caused by:

- The version of the daemon, that's not supporting the mini, then you'll have to clone and build the daemon directly by yourself and launch it in terminal (the UI will be unusable then unfortunately)

- Or, this is just a matter of installation. If you uninstall completely the app (including the files in /launchagent and /launchdaemon that handles the "plug and play" part of the app) and make a clean reinstall it may solve the issue, but i can't tell you that it WILL fix it. You have to try other things like launching the daemon in sudo mode, then plug/unplug the goxlr... If not, don't bother you with the app and just install the daemon and client separately with the newest version xD

I'm sorry that you get theses errors but I didn't thought about the mini at all when creating it ! The #7 will be solving this issue but for now I have to wait for the daemon to be completely finished to avoid having to update everything every time the daemon is updated !
